name: 'Terraform'

on:
  push:
    branches:
    - "main"
    workflow_dispatch:


jobs:

  Terraform:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Terraform Plan
        run: |
          terraform init
          terraform plan
      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-aprove
