name: 'Terraform Apply'

on:
  pull_request:
    types: [closed]
    workflow_dispatch:

env:
  PM_API_URL: https://192.168.1.4:8006/api2/json
  PM_API_TOKEN_ID: root@pam!terraform
  PM_API_TOKEN_SECRET: ${{ secrets.PM_TOKEN }}
  PM_TLS_INSECURE: true


jobs:
  TerraformApply:
    runs-on: [self-hosted]
    container:
      image: hashicorp/terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      
      
