name: 'Terraform Plan'

on:
  push:
    branches:
    - "plan"
    workflow_dispatch:
  pull_request:
    branches:
      - "main"
    workflow_dispatch:

env:
  PM_API_URL: https://192.168.1.4:8006/api2/json
  PM_API_TOKEN_ID: root@pam!terraform
  PM_API_TOKEN_SECRET: ${{ secrets.PM_TOKEN }}
  PM_USER: root 
  PM_PASS: ${{ secrets.PM_PASS }}
  PM_TLS_INSECURE: true
  PROXMOX_VE_USERNAME: root
  PROXMOX_VE_PASSWORD: ${{ secrets.PM_PASS }}
  PROXMOX_VE_ENDPOINT: https://192.168.1.4:8006/api2/json
  PROXMOX_VE_INSECURE: true
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  TerraformPlan:
    runs-on: [self-hosted]
    container:
      image: hashicorp/terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Init Terraform plugins 
        run: terraform init
      - name: Validate terraform files
        run: terraform validate
      - name: Show terraform Plan
        run: terraform plan
      