name: 'Terraform Plan'

on:
  push:
    branches:
    - "plan"
    workflow_dispatch:
  pull_request:
    branches:
      - "main"
    workflow_dispatch:


env:
  TERRAFORM_DOWNLOAD_URL: https://releases.hashicorp.com/terraform/1.2.3/terraform_1.2.3_linux_amd64.zip
  TERRAFORM_SSH_KEY: ${{ secrets.SSH_KEY }}
  CONSUL_ADDRESS: 192.168.1.4:8500
  CONSUL_PATH: state/terra.tfstate
  PM_API_URL: https://192.168.1.4:8006/api2/json
  PM_USER: root@pam 
  PM_PASS: ${{ secrets.PM_PASS }}
  PM_TLS_INSECURE: true
  PROXMOX_VE_USERNAME: root@pam
  PROXMOX_VE_PASSWORD: ${{ secrets.PM_PASS }}
  PROXMOX_VE_ENDPOINT: https://192.168.1.4:8006/
  PROXMOX_VE_INSECURE: 1
  

jobs:
  Validate:
    runs-on: [self-hosted]
    container:
      image: centos:7
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Initialize terraform
        uses: ./.github/actions/initTerraform 
      - name: Validate terraform files
        run: terraform validate
  Plan:
    needs: Validate
    runs-on: [self-hosted]
    container:
      image: centos:7
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Initialize terraform
        uses: ./.github/actions/initTerraform 
      - name: Show Terraform plan
        run: terraform plan -out plan
      
      
