name: 'Terraform Apply'

on:
  push:
    branches:
      - main

env:
  TF_VAR_consul_address: 192.168.1.4:8500
  TF_VAR_consul_path: terraform/terraform.tfstate
  PM_API_URL: https://192.168.1.4:8006/api2/json
  PM_USER: root@pam 
  PM_PASS: ${{ secrets.PM_PASS }}
  PM_TLS_INSECURE: true
  PROXMOX_VE_USERNAME: root@pam
  PROXMOX_VE_PASSWORD: ${{ secrets.PM_PASS }}
  PROXMOX_VE_ENDPOINT: https://192.168.1.4:8006/
  PROXMOX_VE_INSECURE: 1
  SSH_KEY: ${{ secrets.SSH_KEY }}


jobs:
  TerraformApply:
    runs-on: [self-hosted]
    environment: production
    container:
      image: centos:7
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Packages
        run: yum install -y openssh wget gettext unzip 
      - name: Install Terraform
        run: |
          wget  -o
          unzip 
      - name: Install SSH Key
        run: |
          mkdir -p /root/.ssh
          chown root /root/.ssh
          echo $SSH_KEY | base64 -d > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa 
      - name: Init Terraform plugins 
        run: terraform init
      - name: Validate terraform files
        run: terraform validate
      - name: Apply terraform files
        run: terraform apply -auto-approve
      - uses: actions/upload-artifact@v2
        with:
          name: key
          path: /root/.ssh
      
      
