name: 'Terraform Plan'

on:
  push:
    branches:
    - "plan"
    workflow_dispatch:
  pull_request:
    branches:
      - "main"
    workflow_dispatch:

env:
  TF_VAR_proxmoxUrl: https://192.168.1.4:8006/api2/json
  TF_VAR_proxmoxToken: root@pam!terraform
  TF_VAR_proxmoxSecret: fdd0f2a1-6cf4-41a2-ba0a-c4f8ea251a6f

jobs:
  TerraformPlan:
    runs-on: [self-hosted]
    container:
      image: hashicorp/terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Display env variables
        run: |
          echo $TF_VAR_proxmoxUrl
          echo $TF_VAR_proxmoxToken
          echo $TF_VAR_proxmoxSecret
      - name: Terraform Init 
        run: terraform init
      - name: Terraform Plan 
        run: terraform plan
      