name: 'Terraform Apply'

on:
  push:
    branches:
      - main

env:
  TERRAFORM_DOWNLOAD_URL: https://releases.hashicorp.com/terraform/1.2.3/terraform_1.2.3_linux_amd64.zip
  TERRAFORM_SSH_KEY: ${{ secrets.SSH_KEY }}
  CONSUL_ADDRESS: 192.168.1.4:8500
  CONSUL_PATH: state/terraform.tfstate
  PM_API_URL: https://192.168.1.4:8006/api2/json
  PM_USER: root@pam 
  PM_PASS: ${{ secrets.PM_PASS }}
  PM_TLS_INSECURE: true
  PROXMOX_VE_USERNAME: root@pam
  PROXMOX_VE_PASSWORD: ${{ secrets.PM_PASS }}
  PROXMOX_VE_ENDPOINT: https://192.168.1.4:8006/
  PROXMOX_VE_INSECURE: 1
  

jobs:
  TerraformApply:
    runs-on: [self-hosted]
    container:
      image: centos:7
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Packages
        run: yum install -y openssh-clients wget gettext unzip 
      - name: Install Terraform
        run: |
          wget $TERRAFORM_DOWNLOAD_URL -O terraform.zip
          unzip terraform.zip
          mv terraform /bin
          chmod +x /bin/terraform
      - name: Install SSH Key for Provisioning
        run: |
          echo $TERRAFORM_SSH_KEY | base64 -d > /tmp/id_rsa
          chmod 600 /tmp/id_rsa 
      - name: Create Consul Backend config
        run:  cat backend.tf.example | envsubst | tee backend.tf
      - name: Init Terraform plugins 
        run: terraform init
      - name: Validate terraform files
        run: terraform validate
      - name: Apply terraform files
        run: terraform apply -auto-approve
      - name: Delete SSH Key for Provisioning
        run: rm -f /tmp/id_rsa
      
      
