name: 'Terraform'

on:
  push:
    branches:
    - "main"
    workflow_dispatch:


jobs:

  Terraform:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        name: Terraform Plan
        run: |
          terraform init
          terraform plan

      - uses: actions/checkout@v2
        name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-aprove
