name: 'Terraform Apply'

on:
  push:
    branches:
      - main

env:
  TERRAFORM_SSH_KEY: ${{ secrets.SSH_KEY }}
  CONSUL_ADDRESS: 192.168.1.4:8500
  CONSUL_PATH: state/terra.tfstate
  PM_API_URL: https://192.168.1.4:8006/api2/json
  PM_USER: root@pam 
  PM_PASS: ${{ secrets.PM_PASS }}
  PM_TLS_INSECURE: true
  PROXMOX_VE_USERNAME: root@pam
  PROXMOX_VE_PASSWORD: ${{ secrets.PM_PASS }}
  PROXMOX_VE_ENDPOINT: https://192.168.1.4:8006/
  PROXMOX_VE_INSECURE: 1
  SSL_CERT_DIR: "/etc/ssl/certs"
  

jobs:
  Validate:
    runs-on: [self-hosted]
    container:
      image: ggmartinez/terraform:1.2.3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Initialize terraform
        uses: ./.github/actions/initTerraform 
      - name: Validate terraform files
        run: terraform validate
  Plan:
    needs: Validate
    runs-on: [self-hosted]
    container:
      image: ggmartinez/terraform:1.2.3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Initialize terraform
        uses: ./.github/actions/initTerraform 
      - name: Show Terraform plan
        run: terraform plan -out plan
      - name: Save plan file
        uses: actions/upload-artifact@v2
        with:
          name: terraformPlan
          path: plan
  Apply:
    needs: Plan
    runs-on: [self-hosted]
    container:
      image: ggmartinez/terraform:1.2.3
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Initialize terraform
        uses: ./.github/actions/initTerraform 
      - name: Download plan file 
        uses: actions/download-artifact@v2
        with:
          name: terraformPlan
      - name: Apply Terraform configuration
        run: terraform apply plan 


      
      
