name: 'Terraform Plan'

on:
  push:
    branches:
    - "plan"
    workflow_dispatch:


jobs:
  Terraform Plan:
    runs-on: [self-hosted]
    container:
      image: hashicorp/terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Terraform Plan
        run: |
          terraform init
          terraform plan